
      # create condition to install dac, based on a variable

      # enable i2s


    - name: installing external-dac
      block:

        # hifiberry-dac overlay
        # dtoverlay=hifiberry-dac
        - name: Adding hifiberry-dac overlay
          become: yes
          lineinfile:
            line: "dtoverlay=hifiberry-dac"
            path: /boot/config.txt

        # disable on-board sound

        - name: Disable on-board sound
          become: yes
          lineinfile:
            path: /boot/config.txt
            regexp: '^dtparam=audio=on'
            line: '#dtparam=audio=on'
          notify:
          - reboot

      when: externaldac == "yes"

    - name: disabling external-dac
      block:

        # hifiberry-dac overlay
        # dtoverlay=hifiberry-dac
        - name: remowe hifiberry-dac overlay
          become: yes
          lineinfile:
            regexp: "^dtoverlay=hifiberry-dac"
            line: "#dtoverlay=hifiberry-dac"
            path: /boot/config.txt

        # disable on-board sound

        - name: Enable on-board sound
          become: yes
          lineinfile:
            path: /boot/config.txt
            regexp: '^#dtparam=audio=on'
            line: 'dtparam=audio=on'
          notify:
          - reboot

      when: externaldac != "yes"



      # managing kernel blacklist

      # in

      # out

      # select samplerate {{ samplerate }} audiobuf 48000

      # select buffersize {{ buffersize }} audiobuf 16

      # select blocksize {{ blocksize }} blocksize 64

      # save data

      # Rebooting or Restart PD
