      # setup adc mcp3008

    - name: Setting mcp3008 | Enable
      block:

        # - name: EXTERNAL DAC | Adding hifiberry-dac overlay
        #   become: yes
        #   lineinfile:
        #     regexp: "^#dtoverlay=hifiberry-dac"
        #     line: "dtoverlay=hifiberry-dac"
        #     path: /boot/config.txt
        #
        # - name: EXTERNAL DAC | Disable on-board sound
        #   become: yes
        #   lineinfile:
        #     path: /boot/config.txt
        #     regexp: '^dtparam=audio=on'
        #     line: '#dtparam=audio=on'
        #   notify:
        #   - reboot

      when: mcp3008 == 'yes'

    - name: Setting mcp3008 | Disable
      block:

        # - name: EXTERNAL DAC | remove hifiberry-dac overlay
        #   become: yes
        #   lineinfile:
        #     regexp: "^dtoverlay=hifiberry-dac"
        #     line: "#dtoverlay=hifiberry-dac"
        #     path: /boot/config.txt
        #
        #
        # - name: EXTERNAL DAC | Enable on-board sound
        #   become: yes
        #   lineinfile:
        #     path: /boot/config.txt
        #     regexp: '^#dtparam=audio=on'
        #     line: 'dtparam=audio=on'
        #   notify:
        #   - reboot

      when: externaldac != 'yes'
