      # setup adc mcp3008

    - name: MCP3008 | Enable
      block:

        # Enable SPI
        - name: MCP3008 | ENABLE SPI
          replace:
            path: /boot/config.txt
            regexp: "#dtparam=spi=on"
            replace: "dtparam=spi=on"

          # regexp: "^#?dtparam=spi"
          #line: "dtparam=spi=on"
        # Copy code or libraries
        # Set pd externals on the path
        # just need to ship it with the patch
        #- name: Remove Blacklist files
        #  file:
        #    state: absent
        #    path: /etc/modproble.d/raspi-blacklist.conf

        # or "sudo dtparam spi"



      when: mcp3008 == 'yes'

    # - name: MCP3008 | Disable
    #   block:
    #
    #     # Disable SPI
    #     - name: MCP3008 | DISABLE SPI
    #       replace:
    #         path: /boot/config.txt
    #         regexp: "^#?dtparam=spi"
    #         line: "dtparam=spi=off"
    #
    #
    #   when: mcp3008 != 'yes'
