      # setup adc mcp3008

  - name: MPR121 | Enable
    block:

      - name: MPR121 | Install git python-dev smbus pip puredata-utils screen
        become: yes
        package: name={{ item }} state=latest
        with_items:
          - git
          - python-dev
          - python-smbus
          - python-pip
          - puredata-utils
          - screen

      - name: MPR121 | git clone Adafruit_Python_MPR121
        #become: yes
        git:
          repo: https://github.com/adafruit/Adafruit_Python_MPR121.git
          dest: /home/pi/Adafruit_Python_MPR121

      # cd /home/pi/Adafruit_Python_MPR121
      # sudo python setup.py install
      - name: MPR121 | Install Adafruit_Pynton_MPR121
        become: yes
        command: python setup.py install
        args:
          chdir: /home/pi/Adafruit_Python_MPR121

      - name: MPR121 | Adding i2c-bcm2708 overlay
        become: yes
        lineinfile:
          regexp: "^#dtoverlay=i2c-bcm2708"
          line: "dtoverlay=i2c-bcm2708"
          path: /boot/config.txt

      - name: MPR121 | Adding i2c_arm=on Device Tree Parameter
        become: yes
        lineinfile:
          regexp: "^#dtparam=i2c_arm=on"
          line: "dtparam=i2c_arm=on"
          path: /boot/config.txt

      - name: MPR121 | Adding i2c1=on Device Tree Parameter
        become: yes
        lineinfile:
          regexp: "^#dtparam=i2c1=on"
          line: "dtparam=i2c1=on"
          path: /boot/config.txt

      - name: MPR121 | Add kernel module i2c-dev
        become: yes
        modprobe:
          name: i2c-dev
          state: present

      # doesn't work always? Add it manually to /etc/modules - option
      # - name: MPR121 | Adding kernel module i2c-dev
      #   become: yes
      #   lineinfile:
      #     regexp: "^i2c-dev"
      #     line: "i2c-dev"
      #     path: /etc/modules

      # copy python script
      - name: MPR121 | Install mpr121-pd.py script
        become: yes
        copy:
          src: "../externals/mpr121-pd.py"
          dest: "/root/"
          mode: 0700

      # execute at boot
      - name: MPR121 | Copy unit for execute mpr121-pd.py at boot
        become: yes
        copy:
          src: "../externals/mpr121-pd.service"
          dest: "/etc/systemd/system"
          mode: 0744

      - name: enable service mpr121-pd and ensure it is not masked
        systemd:
          name: mpr121-pd
          enabled: yes
          masked: no
        notify:
        - reboot



    when: mpr121 == 'yes'

# try to not remove anything when mpr121 != 'yes'
