    - name: PCM5102A | Enable
      block:

        # hifiberry-dac overlay
        # dtoverlay=hifiberry-dac
        - name: PCM5102A | Adding hifiberry-dac overlay
          become: yes
          lineinfile:
            regexp: "^#dtoverlay=hifiberry-dac"
            line: "dtoverlay=hifiberry-dac"
            path: /boot/config.txt

        # disable on-board sound
        #
        # - name: PCM8251A | Disable on-board sound
        #   become: yes
        #   lineinfile:
        #     path: /boot/config.txt
        #     regexp: '^dtparam=audio=on'
        #     line: '#dtparam=audio=on'
        #   notify:
        #   - reboot

      when: pcm5102a == 'yes'
