      - name: PERFORMANCE | Set vm.swappiness to 10 in sysctl.conf
        become: yes
        sysctl:
          name: vm.swappiness
          value: 10
          state: present

      - name: PERFORMANCE | Set fs.inotify.max_user_watches to 524288 in systctl.conf
        become: yes
        sysctl:
          name: fs.inotify.max_user_watches
          value: 524288
          state: present

      - name: set pi gpu mem to 16
        become: true
        lineinfile:
          path: /boot/config.txt
          regexp: 'gpu_mem.*'
          line: 'gpu_mem=16'
          owner: root
          group: root
          mode: 0755


      # Install linux-cpupower
      - name: PERFORMANCE | Installing cpufreq-set by cpufrequtils package
        become: yes
        package:
          name: cpufrequtils
          state: latest

      # sudo cpufreq-set -c <cpunr> -g performance'
      - name: PERFORMANCE | Setting performance governor on all CPUs
        become: yes
        shell: "cpufreq-set -g performance"
        register: performance

      - name: PERFORMANCE | Check autorun governor performance
        cron:
          name: cpufreq performance
          reboot: yes
          job: "cpufreq-set -g performance"
          state: present

      # removing packages
      - name: REMOVING | ntp, triggerhappy
        become: yes
        package: name={{ item }} state=absent
        with_items:
          - ntp
          - triggerhappy
          #- dbus
