# Update apt packages
- name: PUREDATA | Update apt packages
  become: yes
  apt:
    update_cache=yes

# Installing pd and vim. Maybe swith to puredata-core
- name: PUREDATA | Installing pd, rsync and vim
  become: yes
  package: name={{ item }} state=latest
  with_items:
    - vim
    - puredata-core
    - rsync

# check `which startx` to understand if there is X system to install
- name: PUREDATA | Checking X windows installed
  stat:
    path: /usr/bin/startx
  register: stat_startx

- name: PUREDATA | install pd-gui x11vnc if X windows are available
  become: yes
  package: name={{ item }} state=latest
  with_items:
    - puredata-gui
    - x11vnc
  when: stat_startx.stat.exists == True

# save data
- name: PUREDATA | Saving settings to /home/pi/.pdsettings
  template:
    src: "../templates/pdsettings"
    dest: "/home/pi/.pdsettings"

- name: PUREDATA | Saving settings to /root/.pdsettings
  template:
    src: "../templates/pdsettings"
    dest: "/root/.pdsettings"

# print pdsettings
#- name: Printing /home/pi/.pdsettings
#  shell: cat /home/pi/.pdsettings
#  register: pdsettings

#- debug: msg="{{ pdsettings.stdout_lines }}"
