      # setup adc mcp3008

  - name: Switches | Enable
    block:

      - name: Switches | pip install wiringpi
        become: yes
        command: pip install wiringpi

      # copy python script
      - name: Switches | Install switchesread.py script
        become: yes
        copy:
          src: "../externals/switchesread.py"
          dest: "/root/"
          mode: 0700

      # execute at boot
      - name: Switches | Copy unit for execute switchesread.py at boot
        become: yes
        copy:
          src: "../externals/switchesread.service"
          dest: "/etc/systemd/system"
          mode: 0744

      - name: Switches | enable service switchesread and ensure it is not masked
        systemd:
          name: switchesread
          enabled: yes
          masked: no
        notify:
        - reboot

    when: switches == 'yes'

# try to not remove anything when mpr121 != 'yes'
