# ansible-playbook -i ~/ansible/hosts /playbooks/clean-packages.yml

---
- hosts: defaultdevices
  gather_facts: yes

  tasks:
      - name: Clean Apt packages
        command: apt-get clean
        become: yes
