# ansible-playbook -i ~/ansible/hosts /playbooks/mount-ro.yml
# Created by Victor Sanahuja 20170731
---
- hosts: defaultdevices
  gather_facts: yes

  role:
    - DinoTools.raspi_ro_root

  tasks:
      # switch filesystem to readonly on fstab, use regexp?
    - name: Switch to readonly
      raspi_ro_root_enabled: yes
      raspi_ro_root_state_change_reboot: yes
