# ansible-playbook -i ~/ansible/hosts /playbooks/realtime-kernel.yml
# Created by Victor Sanahuja 20170731
---
- hosts: defaultdevices
  gather_facts: yes

  tasks:

    # Required git depend
    - name: Install git
      become: yes
      package:
        name: git
        state: latest

    # Download repo https://github.com/piscue/Realtime-Kernel-RaspberryPi.git
    - name: Downloading pre-compiled kernel from piscue's repo
      become: yes
      git:
        repo: https://github.com/piscue/Realtime-Kernel-RaspberryPi.git
        dest: /home/pi/Realtime-Kernel-RaspberryPi

    - name: Install Realtime Kernel using rsync
      become: yes
      synchronize:
        src: "/home/pi/Realtime-Kernel-RaspberryPi/boot"
        dest: /
        # avoid ownership problems
        archive: no
        recursive: yes
      # for local transfer on the remote host
      delegate_to: "{{ inventory_hostname }}"
      register: rsynclog

    #- debug: msg="{{ rsynclog.stdout_lines }}"

    - name: Install Realtime Modules using rsync
      become: yes
      synchronize:
        src: "/home/pi/Realtime-Kernel-RaspberryPi/lib"
        dest: /
        # avoid ownership problems
        archive: no
        recursive: yes
      # for local transfer on the remote host
      delegate_to: "{{ inventory_hostname }}"
      register: rsyncmoduleslog
      notify:
        - reboot



  handlers:

    - include: ../handlers/reboot.yml
      tags: system
